# =============================================
# Conexión a PostgreSQL - Northwind
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/northwind
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================
# JPA / Hibernate
# =============================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =============================================
# Servidor
# =============================================
server.port=8080
